### ISSUE TITLE
AMF pod crash when Mobile data disable and re-enable

### ISSUE THREAD

**Issue by ashithacdac** [5GC-DEV/amf-cdac#10]
Issue/Feature Description:
To fix the AMF pod crash issue when Mobile data disabled and enabled

Why this issue to fixed / feature is needed(give scenarios or use cases):
To make the core stable by making the PDU session connection persist from core to UE when mobile data disabled and re-enabled

How to reproduce, in case of a bug:
The Test case has been captured as testcase file Testcase_mobile data_disable and re-enable.xlsx

Other Notes / Environment Information: (Please give the env information, log link or any useful information for this issue)

**Comment by anaswarac-dac** [comment]
Bug Fixed.
